import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "VetWise",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}><div>
        <Toaster toastOptions={{
          position: "bottom-right",
          style:{
            background: "rgb(51 65 85)",
            color: '#fff',
          }
        }}/>
        {children}
        </div></body>
    </html>
  );
}
